management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: SnowCalculatorBackend
    description: A backend for snow license calculator
    author: Younes Elhamss
spring:
  profiles:
    active: dev